Scheduler Feature
Direxfire/55ATAT pull request #6
Opened 2024-09-24 07:26 UTC by DrewTCurrie

## Bringing automatic report generation into the development branch for stable testing. 

This feature allows for the automatic generation of reports on a weekly and monthly basis. 

As is the Flask App now creates a thread that monitors the current time and checks if today is a day that a report needs created at 5:00PM. 

The time is monitored through this function:

```python
def ScheduleManager():
    while 1: 
        schedule.run_pending()
        time.sleep(5)
```

The sleep time is adjustable in code, right now it is at 5 seconds for continued testing, however this needs changed to 1800 to check only every half hour. This will provide a time window of -0 minutes +31 minutes to monthly report generation and -0 minutes +30 minutes to weekly report generation. 

Report generation is calculated based on the current date & time and using a timedelta of 1 week or 4 weeks for a weekly and monthly report respectively. 

```python
def weekly_reports():
    print("Weekly report generation called.")
    fileName = generateReport.generate_spreadsheet(start_date=(datetime.now() - timedelta(weeks= 1)).strftime("%Y-%m-%dT%H:%M:%S.%fZ"))
    print(fileName)
    #TODO: Link with flaskMail to send an email with the attachment. 

def monthly_reports():
    print("Montly report generation called.")
    fileName = generateReport.generate_spreadsheet(start_date=(datetime.now() - timedelta(weeks= 4)).strftime("%Y-%m-%dT%H:%M:%S.%fZ"))
    print(fileName)

```

>[!WARNING]
>This does not contain anyway to download the report automatically. Some research shows that flask-mail may be the best option for this but we need to access PTC's mailing service for this to work.

2024-09-24 17:04 UTC, samlovering requested changes
https://github.com/DrewTCurrie/55ATAT/pull/6/commits/c52dff07810561467aee2f696867f501cf9d4f51

This commit is causing issues, it merged in the Pi's ptcClient/node_modules folder, and crashes my browser most times I try to review the code. 

Additionally the node_modules folder have appeared the shell-scripts folder. 

The original commit where node_modules got added to  is here: https://github.com/DrewTCurrie/55ATAT/commit/46a3464735e2ffccf804875d20797751c67719c8

2024-09-24 20:19 UTC, DrewTCurrie commented
> [c52dff0](https://github.com/DrewTCurrie/55ATAT/commit/c52dff07810561467aee2f696867f501cf9d4f51)
> 
> This commit is causing issues, it merged in the Pi's ptcClient/node_modules folder, and crashes my browser most times I try to review the code.
> 
> Additionally the node_modules folder have appeared the shell-scripts folder.
> 
> The original commit where node_modules got added to is here: [46a3464](https://github.com/DrewTCurrie/55ATAT/commit/46a3464735e2ffccf804875d20797751c67719c8)

I removed the node_modules from the pi. I also suspect it could be the IP address of the pi causing issues. I had to use a hard coded IP address otherwise it would try and route through MSU's network for some reason. I could fix the issue by either disabling the wireless connection from Pi to MSU-Secure or by hard coding the local ethernet IP.

2024-09-24 20:22 UTC, samlovering commented
I updated the gitignore/deleted the files on the dev branch. it should
prevent this again down the line

On Tue, Sep 24, 2024, 2:19 PM DrewC ***@***.***> wrote:

> c52dff0
> <https://github.com/DrewTCurrie/55ATAT/commit/c52dff07810561467aee2f696867f501cf9d4f51>
>
> This commit is causing issues, it merged in the Pi's
> ptcClient/node_modules folder, and crashes my browser most times I try to
> review the code.
>
> Additionally the node_modules folder have appeared the shell-scripts
> folder.
>
> The original commit where node_modules got added to is here: 46a3464
> <https://github.com/DrewTCurrie/55ATAT/commit/46a3464735e2ffccf804875d20797751c67719c8>
>
> I removed the node_modules from the pi. I also suspect it could be the IP
> address of the pi causing issues. I had to use a hard coded IP address
> otherwise it would try and route through MSU's network for some reason. I
> could fix the issue by either disabling the wireless connection from Pi to
> MSU-Secure or by hard coding the local ethernet IP.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DrewTCurrie/55ATAT/pull/6#issuecomment-2372296542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCADRN5W54N6WQK2WU36HPLZYHCN5AVCNFSM6AAAAABOXUHDSOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNZSGI4TMNJUGI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-09-25 01:15 UTC, samlovering approved these changes

2024-10-06 22:38 UTC, closed without merging